---
#<% require 'kitchen-sync' %>
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[postgresql::server]
      - recipe[poise-graphite-test::default]
    attributes:
      qosp_repo:
        use_dev: true
      postgresql:
        password:
          postgres: 'reallybadpassword'
        config:
          ssl: off
