---
driver:
  name: digital_ocean
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_token: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>
  ssh_keys: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>

provisioner:
  name: chef_solo
  require_chef_omnibus: latest
platforms:
- name: ubuntu-14.04
  run_list:
    - recipe[apt]
