---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[qosp_repo]
      - recipe[graphite-test::default]
    attributes:
      qosp_repo:
        use_dev: true
